name: papers-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - scipy=1.16.3
  - jupyter=1.1.1
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - statsmodels=0.14.5
  - pandas-datareader=0.10.0
  - geopandas=1.1.1
  - fiona
  - matplotlib=3.10.6
  - pandas=2.3.3
  - numpy=2.3.4
prefix: /opt/miniconda3/envs/papers-env
